@startuml
' to generate svg from puml use:
' plantuml -tsvg CreateCustomer.puml
' details https://plantuml.com/command-line
title Lambda Architecture KISS

participant "API Gateway" as API
participant "**<U+03BB>**\nCreateUser" as handler
participant "CreateUserService" as service
database "DynamoDB-UserTable" as DynamoDB


API -> handler: CreateUser

handler -> handler: validate-event
opt invalid event
    handler -> API: 400 Error "event is invalid."
end
handler -> service: create-user(model)
service -> service: generate-id
service -> service: map-to-dynamo-db-entity

opt invalid entity
    service -> API: ProxyIntegrationError "entity is invalid."
end

service -> DynamoDB: put
opt invalid entity
    DynamoDB -> API: 400 ProxyIntegrationError "operation error"
end

DynamoDB -> service: OK
service -> handler: {id: "GUID"}
handler -> API: 201 Created {id: "GUID"}

@enduml
