@startuml
' to generate svg from puml use:
' plantuml -tsvg CreateCustomer.puml
' details https://plantuml.com/command-line
title Lambda Architecture N-Layer

participant "API Gateway" as API
participant "**<U+03BB>**\nCreateUser" as handler
participant "**<U+03BB>**\nCreateUserService" as service
participant "**<U+03BB>**\nUserRepository" as repository
database "DynamoDB-UserTable" as DynamoDB


API -> handler: CreateUser

handler -> handler: validate-event
opt invalid event
    handler -> API: 400 Error "event is invalid."
end
handler -> service: create-user(model)
service -> service: generate-id
service -> service: map-to-entity

service --> repository: put-item
repository -> repository: validate-entity
opt invalid entity
    repository -> API: ProxyIntegrationError "entity is invalid."
end

repository -> DynamoDB: put
opt invalid entity
    DynamoDB -> API: 400 ProxyIntegrationError "operation error"
end
DynamoDB -> repository: OK
repository -> service: {id: "GUID"}
service -> handler: {id: "GUID"}
handler -> API: 201 Created {id: "GUID"}

@enduml
