
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# https://ardalis.com/rest-commands-and-queries-in-vs-code

@ApiGatewayHostname =  https://x.execute-api.eu-central-1.amazonaws.com/beta/
@GraphQLHost = https://x.appsync-api.eu-central-1.amazonaws.com/graphql
@GraphQLAppSyncApiKey = x

@port = 7071
#@hostname = http://localhost:{{port}}/api

@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}

###
### users
###
GET {{ApiGatewayHostname}}/users HTTP/1.1
###
### create user
###
POST {{ApiGatewayHostname}}/users HTTP/1.1
content-type: {{contentType}}

{
    "email": "{{$guid}}"
}



###
### GraphQL users
### 
POST {{GraphQLHost}} HTTP/1.1
Content-Type: {{contentType}}
x-api-key: {{GraphQLAppSyncApiKey}}
X-REQUEST-TYPE: GraphQL

query {
  listUsers {
    items {
      email
      id
    }
  }
}

###
### GraphQL user by id
### 
POST {{GraphQLHost}} HTTP/1.1
Content-Type: {{contentType}}
x-api-key: {{GraphQLAppSyncApiKey}}
X-REQUEST-TYPE: GraphQL

query {
   getUserById(id: "2b07f790-8671-4c0f-9128-052cc5c7135f") {
    email
    id
  }
}