name: build

on: [push]

jobs:
  aws_cdk:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Setup dependencies
        run: npm run setup

      - name: Build
        run: npm run build
        env:
          ENV: development

      - name: Run eslint
        run: npm run lint

      - name: Unit Test
        if: contains(github.event_name, 'pull_request')
        run: npm run test

      - name: CDK Diff Check
        if: contains(github.event_name, 'pull_request')
        run: npm run cdk:diff
        env:
          ENV: development
          AWS_DEFAULT_REGION: 'eu-central-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

#      - name: CDK Setup and Bootstrap
#        if: contains(github.event_name, 'push')
#        run: rm -rf ./node_modules && rm -rf ./src/node_modules && npm run setup:production && npm install -g aws-cdk && cdk bootstrap
#        env:
#          ENV: development
#          AWS_DEFAULT_REGION: 'ap-northeast-1'
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#
#      - name: CDK Deploy
#        if: contains(github.event_name, 'push')
#        run: cdk deploy --require-approval never
#        env:
#          ENV: development
#          AWS_DEFAULT_REGION: 'ap-northeast-1'
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}