name: build

on:
  # run it on push to the default repository branch
  push:
    branches: [$default-branch]
  # run it during pull request
  pull_request:


jobs:
  build:
    # use system defined below in the tests matrix
    runs-on: ${{ matrix.os }}

    strategy:
      # define the test matrix
      matrix:
        # selected operation systems to run CI
        os: [ubuntu-latest]
        # selected node version to run CI
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          # use the node version defined in matrix above
          node-version: ${{ matrix.node-version }}

      #CDK - global install
      # install dependencies
      - run: npm ci
      # run linting (ESlint and Prettier)
      - run: npm run lint

      # lambda assets
      # install dependencies
      - name: install assets lambda depedencies
        working-directory: ./assets/lambda
        run: npm ci
      # run build all
      - name: build assets lambda build
        run: npm run build:all
      # run tests
      - run: npm run test:unit
